# Generated by Django 3.0.2 on 2020-04-19 06:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200325_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address_n', 'verbose_name_plural': 'address_n'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='content',
        ),
        migrations.RemoveField(
            model_name='address',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='address',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='address',
            name='fix_time',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='address',
            name='addr',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AddField(
            model_name='address',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 19, 6, 47, 53, 677074, tzinfo=utc), verbose_name='creating time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='deleting marks'),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='address',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updating time'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterModelTable(
            name='address',
            table='df_address',
        ),
    ]
