# Generated by Django 3.0.2 on 2020-04-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='descripton',
            new_name='description',
        ),
    ]
