# Generated by Django 3.0.2 on 2020-04-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_auto_20200405_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishtype',
            name='dish',
        ),
        migrations.AddField(
            model_name='dishtype',
            name='path',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='dishtype',
            name='pid',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='dish',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='fix_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='fix_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
