# Generated by Django 3.0.2 on 2020-04-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_auto_20200406_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishtype',
            name='path',
        ),
        migrations.RemoveField(
            model_name='dishtype',
            name='pid',
        ),
    ]
