# Generated by Django 3.0.2 on 2020-04-06 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_auto_20200406_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='typeid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='dish_all_types', to='dish.DishType'),
        ),
    ]
