# Generated by Django 3.0.2 on 2020-04-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0005_dish_typeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dishId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dishtype',
            name='typeId',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
