# Generated by Django 3.0.2 on 2020-03-24 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='user.Address'),
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdishes',
            name='dish',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='dish.Dish'),
        ),
        migrations.AddField(
            model_name='orderdishes',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='order.OrderInformation'),
        ),
    ]
